/**
 * Demo corpus.
 *
 * These profiles are written directly rather than generated by running real
 * interviews, so `npm run db:seed` works with no API key and costs nothing. The
 * shape matches exactly what the finish route produces, so manager search and the
 * candidate report render the same way they will with real data.
 *
 * Every person here is invented.
 */

import { PrismaClient } from "@prisma/client";
import { embed } from "../src/lib/embeddings";

const db = new PrismaClient();

type Seed = {
  name: string;
  email: string;
  location: string;
  headline: string;
  sector: string;
  seniority: string;
  roleTitle: string;
  years: number;
  score: number;
  recommendation: string;
  summary: string;
  competencies: { competencyId: string; label: string; score: number; confidence: "low" | "medium" | "high"; evidence: string; note: string }[];
  strengths: string[];
  concerns: string[];
  tags: { label: string; kind: string; confidence: number; status: string; evidence: string }[];
};

const SEEDS: Seed[] = [
  {
    name: "Mira Okonkwo",
    email: "mira.okonkwo@example.com",
    location: "Berlin",
    headline: "Senior ML engineer, recommendation systems",
    sector: "engineering",
    seniority: "senior",
    roleTitle: "Senior machine learning engineer",
    years: 7,
    score: 84,
    recommendation: "strong_yes",
    summary:
      "Deep, specific knowledge of production recommendation systems, with unusually honest "
      + "accounting of what did not work. Walked through a retrieval regression she caused and "
      + "diagnosed, including the instrumentation she added to discriminate between two "
      + "hypotheses. Main reservation is limited exposure to serving infrastructure below the "
      + "model layer.",
    competencies: [
      { competencyId: "technical_depth", label: "Technical depth", score: 89, confidence: "high", evidence: "explained why their two-tower model degraded when the item embedding table was refreshed asynchronously", note: "Depth held up across three consecutive follow-ups." },
      { competencyId: "system_design", label: "System design", score: 71, confidence: "medium", evidence: "sketched the candidate-generation and ranking split, but was vague on the feature store", note: "Strong at the model layer, thinner below it." },
      { competencyId: "debugging", label: "Debugging and rigour", score: 88, confidence: "high", evidence: "added a shadow ranker to isolate whether the regression was retrieval or ranking", note: "Textbook hypothesis discrimination." },
      { competencyId: "code_quality", label: "Code and craft", score: 74, confidence: "medium", evidence: "described dropping test coverage on experiment code deliberately, with a rationale", note: "Has a position and can defend it." },
      { competencyId: "logical_reasoning", label: "Logical reasoning", score: 85, confidence: "high", evidence: "revised her estimate unprompted when told the traffic assumption was 10x off", note: "Updates cleanly on new constraints." },
      { competencyId: "communication", label: "Communication", score: 80, confidence: "high", evidence: "compressed the whole incident into two sentences when asked", note: "Calibrates depth well." },
      { competencyId: "ownership", label: "Ownership and judgement", score: 86, confidence: "high", evidence: "I shipped the async refresh and I did not think about staleness", note: "Owns failure without theatre." },
      { competencyId: "collaboration", label: "Collaboration and conflict", score: 72, confidence: "medium", evidence: "described losing an architecture argument and implementing the other approach well", note: "Fair to the opposing view." },
    ],
    strengths: [
      "Diagnosed a production regression by building an isolation harness rather than guessing.",
      "Distinguishes clearly between what she built and what her team built.",
      "Comfortable saying she does not know, which made the rest of her answers more credible.",
    ],
    concerns: [
      "Serving and infrastructure below the model layer went largely untested.",
      "All examples come from one company, so adaptability to a different stack is unevidenced.",
    ],
    tags: [
      { label: "PyTorch", kind: "tool", confidence: 0.92, status: "demonstrated", evidence: "described a custom sampler and why the default one skewed the negatives" },
      { label: "Recommendation systems", kind: "domain", confidence: 0.95, status: "demonstrated", evidence: "two-tower retrieval, candidate generation, ranking split" },
      { label: "Python", kind: "skill", confidence: 0.9, status: "demonstrated", evidence: "" },
      { label: "Embeddings", kind: "skill", confidence: 0.88, status: "demonstrated", evidence: "item embedding staleness diagnosis" },
      { label: "A/B testing", kind: "skill", confidence: 0.76, status: "demonstrated", evidence: "shadow ranker comparison" },
      { label: "Kubernetes", kind: "tool", confidence: 0.3, status: "claimed", evidence: "" },
      { label: "Spark", kind: "tool", confidence: 0.55, status: "claimed", evidence: "" },
      { label: "Ranking", kind: "domain", confidence: 0.9, status: "demonstrated", evidence: "" },
      { label: "MLOps", kind: "domain", confidence: 0.45, status: "claimed", evidence: "" },
    ],
  },
  {
    name: "Daniel Reyes",
    email: "daniel.reyes@example.com",
    location: "Singapore",
    headline: "Backend engineer, payments infrastructure",
    sector: "engineering",
    seniority: "mid",
    roleTitle: "Backend engineer",
    years: 4,
    score: 68,
    recommendation: "yes",
    summary:
      "Solid payments-domain knowledge and a real grasp of idempotency and reconciliation, which "
      + "is rarer than it should be. Technical depth is good within payments and thin outside it. "
      + "PyTorch appears on the resume but the interview did not support it.",
    competencies: [
      { competencyId: "technical_depth", label: "Technical depth", score: 70, confidence: "high", evidence: "explained why they key idempotency on request hash rather than client-supplied id", note: "Strong inside payments, narrow outside." },
      { competencyId: "system_design", label: "System design", score: 66, confidence: "medium", evidence: "reasoned about double-charge failure modes before happy path", note: "Failure-first instinct is good." },
      { competencyId: "debugging", label: "Debugging and rigour", score: 62, confidence: "medium", evidence: "traced a reconciliation mismatch to a timezone boundary", note: "Methodical if slow." },
      { competencyId: "code_quality", label: "Code and craft", score: 65, confidence: "low", evidence: "brief mention of contract tests", note: "Barely tested in this interview." },
      { competencyId: "logical_reasoning", label: "Logical reasoning", score: 64, confidence: "medium", evidence: "worked through the retry-storm scenario systematically", note: "" },
      { competencyId: "communication", label: "Communication", score: 71, confidence: "high", evidence: "defined settlement versus authorisation without being asked", note: "Explains jargon unprompted." },
      { competencyId: "ownership", label: "Ownership and judgement", score: 60, confidence: "medium", evidence: "mostly we rather than I on the larger project", note: "Individual contribution was hard to isolate." },
      { competencyId: "collaboration", label: "Collaboration and conflict", score: 66, confidence: "low", evidence: "one thin example", note: "Not really tested." },
    ],
    strengths: [
      "Genuine understanding of idempotency and reconciliation, explained from first principles.",
      "Thinks about failure modes before the happy path.",
    ],
    concerns: [
      "PyTorch is listed on the resume but the interview found no supporting experience.",
      "Hard to separate his contribution from his team's on the flagship project.",
    ],
    tags: [
      { label: "Payments", kind: "domain", confidence: 0.9, status: "demonstrated", evidence: "authorisation, settlement, reconciliation" },
      { label: "Go", kind: "tool", confidence: 0.82, status: "demonstrated", evidence: "" },
      { label: "PostgreSQL", kind: "tool", confidence: 0.78, status: "demonstrated", evidence: "transaction isolation discussion" },
      { label: "Idempotency", kind: "skill", confidence: 0.88, status: "demonstrated", evidence: "request-hash keying rationale" },
      { label: "PyTorch", kind: "tool", confidence: 0.1, status: "contradicted", evidence: "could not describe any model they had trained" },
      { label: "Kafka", kind: "tool", confidence: 0.6, status: "claimed", evidence: "" },
      { label: "PCI DSS", kind: "credential", confidence: 0.5, status: "claimed", evidence: "" },
    ],
  },
  {
    name: "Sofia Lindqvist",
    email: "sofia.lindqvist@example.com",
    location: "Stockholm",
    headline: "Credit risk analyst, structured products",
    sector: "finance",
    seniority: "senior",
    roleTitle: "Senior credit risk analyst",
    years: 9,
    score: 79,
    recommendation: "yes",
    summary:
      "Unusually strong on the limits of her own models — volunteered the assumption that broke "
      + "during a stress episode before being asked. Regulatory knowledge is connected to actual "
      + "decisions rather than recited. Communication is dense and would need work for a "
      + "committee-facing role.",
    competencies: [
      { competencyId: "quantitative", label: "Quantitative reasoning", score: 87, confidence: "high", evidence: "stated the correlation assumption that broke and by roughly how much", note: "Knows where her numbers come from." },
      { competencyId: "financial_acumen", label: "Financial acumen", score: 82, confidence: "high", evidence: "walked a default through to the capital impact", note: "Fluent across statements." },
      { competencyId: "risk_judgement", label: "Risk and control", score: 85, confidence: "high", evidence: "described overriding a model output and documenting why", note: "Treats controls as load-bearing." },
      { competencyId: "regulatory", label: "Regulatory awareness", score: 78, confidence: "medium", evidence: "IFRS 9 staging changed a provisioning decision she made", note: "Connected to practice." },
      { competencyId: "logical_reasoning", label: "Logical reasoning", score: 80, confidence: "high", evidence: "identified that her own conclusion did not follow when the horizon changed", note: "" },
      { competencyId: "communication", label: "Communication", score: 58, confidence: "high", evidence: "three requests for a plainer restatement before it landed", note: "Dense; assumes the listener's context." },
      { competencyId: "ownership", label: "Ownership and judgement", score: 80, confidence: "high", evidence: "owned a provisioning call that turned out conservative", note: "" },
      { competencyId: "collaboration", label: "Collaboration and conflict", score: 74, confidence: "medium", evidence: "described a disagreement with the front office fairly", note: "" },
    ],
    strengths: [
      "Volunteers the weaknesses of her own models before being asked.",
      "Regulation is connected to specific decisions rather than recited as definitions.",
    ],
    concerns: [
      "Explanations are dense; a committee-facing role would need coaching.",
      "All experience is in one asset class.",
    ],
    tags: [
      { label: "Credit risk", kind: "domain", confidence: 0.94, status: "demonstrated", evidence: "" },
      { label: "IFRS 9", kind: "domain", confidence: 0.85, status: "demonstrated", evidence: "staging decision" },
      { label: "Stress testing", kind: "skill", confidence: 0.88, status: "demonstrated", evidence: "correlation assumption breakdown" },
      { label: "Python", kind: "tool", confidence: 0.7, status: "demonstrated", evidence: "" },
      { label: "SQL", kind: "tool", confidence: 0.75, status: "demonstrated", evidence: "" },
      { label: "Basel III", kind: "domain", confidence: 0.6, status: "claimed", evidence: "" },
      { label: "Structured products", kind: "domain", confidence: 0.9, status: "demonstrated", evidence: "" },
    ],
  },
  {
    name: "Adaeze Balogun",
    email: "adaeze.balogun@example.com",
    location: "London",
    headline: "People lead, high-growth technology",
    sector: "hr",
    seniority: "lead",
    roleTitle: "Head of people",
    years: 11,
    score: 81,
    recommendation: "strong_yes",
    summary:
      "Has actually run a reduction in force and described it with specifics most candidates "
      + "avoid — the sequencing, what she got wrong about notification order, and what she "
      + "changed afterwards. Strong on employment practice. Less convincing on connecting people "
      + "programmes to measurable business outcomes.",
    competencies: [
      { competencyId: "people_judgement", label: "People judgement", score: 84, confidence: "high", evidence: "described revising her read on a manager after seeing skip-level data", note: "Evidence over instinct." },
      { competencyId: "difficult_conversations", label: "Difficult conversations", score: 90, confidence: "high", evidence: "walked through a 40-person RIF including the notification order she got wrong", note: "Rare specificity." },
      { competencyId: "employment_practice", label: "Employment practice", score: 83, confidence: "high", evidence: "explained why consultation timelines changed the sequencing in the UK entity", note: "" },
      { competencyId: "org_design", label: "Organisational thinking", score: 64, confidence: "medium", evidence: "described a referral bonus without predicting how it would be gamed", note: "Weaker on second-order effects." },
      { competencyId: "logical_reasoning", label: "Logical reasoning", score: 72, confidence: "medium", evidence: "", note: "" },
      { competencyId: "communication", label: "Communication", score: 88, confidence: "high", evidence: "structured every answer before diving in", note: "" },
      { competencyId: "ownership", label: "Ownership and judgement", score: 85, confidence: "high", evidence: "I sequenced the notifications badly and two people found out from a colleague", note: "" },
      { competencyId: "collaboration", label: "Collaboration and conflict", score: 82, confidence: "high", evidence: "stated the CFO's position fairly before disagreeing with it", note: "" },
    ],
    strengths: [
      "Has genuinely done the hardest parts of the job and describes them without varnish.",
      "Strong grasp of consultation obligations across jurisdictions.",
      "Fair to positions she disagreed with.",
    ],
    concerns: [
      "Weaker at anticipating how a policy will be gamed.",
      "Limited evidence connecting people programmes to business metrics.",
    ],
    tags: [
      { label: "Employee relations", kind: "domain", confidence: 0.92, status: "demonstrated", evidence: "" },
      { label: "Redundancy consultation", kind: "skill", confidence: 0.9, status: "demonstrated", evidence: "40-person RIF" },
      { label: "Performance management", kind: "skill", confidence: 0.8, status: "demonstrated", evidence: "" },
      { label: "UK employment law", kind: "domain", confidence: 0.83, status: "demonstrated", evidence: "consultation timelines" },
      { label: "Compensation design", kind: "skill", confidence: 0.55, status: "claimed", evidence: "" },
      { label: "HRIS", kind: "tool", confidence: 0.5, status: "claimed", evidence: "" },
      { label: "Organisational design", kind: "skill", confidence: 0.6, status: "demonstrated", evidence: "" },
    ],
  },
  {
    name: "Tomás Ferreira",
    email: "tomas.ferreira@example.com",
    location: "Lisbon",
    headline: "Product manager, developer tools",
    sector: "product",
    seniority: "mid",
    roleTitle: "Product manager",
    years: 5,
    score: 62,
    recommendation: "leaning_yes",
    summary:
      "Good user instincts and a genuine example of killing a feature he had championed. "
      + "Measurement is the weak spot — described metrics moving without a baseline or holdout, "
      + "and did not push back when the causal claim was questioned. Worth a second conversation "
      + "focused on experiment design.",
    competencies: [
      { competencyId: "user_insight", label: "User insight", score: 74, confidence: "high", evidence: "described watching a user abandon the flow at a step he had assumed was trivial", note: "Grounded in observation." },
      { competencyId: "prioritisation", label: "Prioritisation", score: 70, confidence: "high", evidence: "killed a feature he had personally pitched", note: "Can actually cut." },
      { competencyId: "execution", label: "Execution", score: 66, confidence: "medium", evidence: "described a slipped launch and the scope cut that saved it", note: "" },
      { competencyId: "metrics", label: "Measurement", score: 42, confidence: "high", evidence: "activation went up 20% after we shipped it, with no holdout", note: "Attributes causally without design." },
      { competencyId: "logical_reasoning", label: "Logical reasoning", score: 55, confidence: "medium", evidence: "did not notice the confound when it was raised", note: "" },
      { competencyId: "communication", label: "Communication", score: 72, confidence: "high", evidence: "", note: "" },
      { competencyId: "ownership", label: "Ownership and judgement", score: 68, confidence: "medium", evidence: "", note: "" },
      { competencyId: "collaboration", label: "Collaboration and conflict", score: 65, confidence: "low", evidence: "", note: "Barely tested." },
    ],
    strengths: [
      "Killed a feature he had championed, and explained the evidence that changed his mind.",
      "Decisions are grounded in specific observed user behaviour.",
    ],
    concerns: [
      "Treats correlation as causation in metric claims; no holdout or baseline discipline.",
      "Did not engage when the confound was pointed out.",
    ],
    tags: [
      { label: "Developer tools", kind: "domain", confidence: 0.8, status: "demonstrated", evidence: "" },
      { label: "User research", kind: "skill", confidence: 0.75, status: "demonstrated", evidence: "" },
      { label: "Roadmapping", kind: "skill", confidence: 0.7, status: "demonstrated", evidence: "" },
      { label: "A/B testing", kind: "skill", confidence: 0.25, status: "contradicted", evidence: "no holdout in the example given" },
      { label: "SQL", kind: "tool", confidence: 0.45, status: "claimed", evidence: "" },
      { label: "API products", kind: "domain", confidence: 0.72, status: "demonstrated", evidence: "" },
    ],
  },
  {
    name: "Hana Sato",
    email: "hana.sato@example.com",
    location: "Tokyo",
    headline: "ML researcher turned applied engineer, computer vision",
    sector: "engineering",
    seniority: "senior",
    roleTitle: "Senior computer vision engineer",
    years: 8,
    score: 77,
    recommendation: "yes",
    summary:
      "Exceptional depth in vision models and training dynamics, with a research background that "
      + "shows in how carefully she qualifies claims. PyTorch knowledge is deep and specific. "
      + "Production and reliability concerns are noticeably less developed than her modelling work.",
    competencies: [
      { competencyId: "technical_depth", label: "Technical depth", score: 92, confidence: "high", evidence: "explained why their augmentation pipeline broke batch-norm statistics at small batch sizes", note: "Very deep, holds across follow-ups." },
      { competencyId: "system_design", label: "System design", score: 55, confidence: "medium", evidence: "vague on inference serving and latency budgets", note: "Research-shaped, not production-shaped." },
      { competencyId: "debugging", label: "Debugging and rigour", score: 84, confidence: "high", evidence: "bisected a training divergence to a specific mixed-precision overflow", note: "" },
      { competencyId: "code_quality", label: "Code and craft", score: 60, confidence: "medium", evidence: "acknowledged research code that nobody could rerun", note: "Honest about it." },
      { competencyId: "logical_reasoning", label: "Logical reasoning", score: 86, confidence: "high", evidence: "qualified a claim unprompted when the evaluation set was questioned", note: "" },
      { competencyId: "communication", label: "Communication", score: 74, confidence: "high", evidence: "", note: "" },
      { competencyId: "ownership", label: "Ownership and judgement", score: 72, confidence: "medium", evidence: "", note: "" },
      { competencyId: "collaboration", label: "Collaboration and conflict", score: 70, confidence: "medium", evidence: "", note: "" },
    ],
    strengths: [
      "Training-dynamics knowledge that survived three levels of follow-up.",
      "Qualifies claims carefully and volunteers the limits of her own evaluations.",
    ],
    concerns: [
      "Production serving, latency, and reliability are underdeveloped relative to modelling.",
      "Research-code habits would need adjusting for a production team.",
    ],
    tags: [
      { label: "PyTorch", kind: "tool", confidence: 0.96, status: "demonstrated", evidence: "batch-norm statistics under small-batch augmentation" },
      { label: "Computer vision", kind: "domain", confidence: 0.94, status: "demonstrated", evidence: "" },
      { label: "CUDA", kind: "tool", confidence: 0.7, status: "demonstrated", evidence: "mixed-precision overflow diagnosis" },
      { label: "Distributed training", kind: "skill", confidence: 0.8, status: "demonstrated", evidence: "" },
      { label: "Python", kind: "skill", confidence: 0.92, status: "demonstrated", evidence: "" },
      { label: "ONNX", kind: "tool", confidence: 0.4, status: "claimed", evidence: "" },
      { label: "Model evaluation", kind: "skill", confidence: 0.85, status: "demonstrated", evidence: "" },
      { label: "Transformers", kind: "skill", confidence: 0.82, status: "demonstrated", evidence: "" },
    ],
  },
];

async function main() {
  console.log("Seeding demo candidates…");

  for (const s of SEEDS) {
    const candidate = await db.candidate.upsert({
      where: { email: s.email },
      create: {
        email: s.email,
        name: s.name,
        location: s.location,
        consentInterview: true,
        consentRecording: true,
        consentLinkCheck: false,
        consentedAt: new Date(),
        consentPolicyVer: "2026-08-23",
      },
      update: { name: s.name, location: s.location },
    });

    const searchText = [
      s.headline,
      `${s.seniority} ${s.roleTitle}`,
      s.sector,
      s.summary,
      s.tags.flatMap((t) => (t.status === "demonstrated" ? [t.label, t.label] : [t.label])).join(" "),
      s.competencies.map((c) => `${c.label} ${c.note}`).join(" "),
    ].join("\n");

    const embedding = await embed(searchText);

    await db.candidateProfile.upsert({
      where: { candidateId: candidate.id },
      create: {
        candidateId: candidate.id,
        headline: s.headline,
        sector: s.sector,
        seniority: s.seniority,
        yearsExperience: s.years,
        overallScore: s.score,
        recommendation: s.recommendation,
        summary: s.summary,
        searchText,
        embedding: JSON.stringify(embedding),
        competencies: JSON.stringify(s.competencies),
      },
      update: {
        headline: s.headline,
        overallScore: s.score,
        summary: s.summary,
        searchText,
        embedding: JSON.stringify(embedding),
        competencies: JSON.stringify(s.competencies),
      },
    });

    for (const t of s.tags) {
      const tag = await db.tag.upsert({
        where: { label: t.label },
        create: { label: t.label, kind: t.kind },
        update: {},
      });
      await db.candidateTag.upsert({
        where: { candidateId_tagId: { candidateId: candidate.id, tagId: tag.id } },
        create: {
          candidateId: candidate.id,
          tagId: tag.id,
          confidence: t.confidence,
          status: t.status,
          evidence: t.evidence || null,
        },
        update: { confidence: t.confidence, status: t.status },
      });
    }

    // A completed interview + assessment so the candidate report page renders.
    const resume = await db.resume.create({
      data: {
        candidateId: candidate.id,
        filename: "seed.txt",
        mimeType: "text/plain",
        rawText: `${s.name}\n${s.headline}\n(seed data)`,
        extracted: JSON.stringify({
          name: s.name, headline: s.headline, totalYearsExperience: s.years,
          employment: [], education: [], skills: [], notableClaims: [], links: [],
          email: s.email, phone: "", location: s.location, summary: s.summary,
          sector: s.sector, seniority: s.seniority, gapsOrOddities: [],
        }),
      },
    });

    const interview = await db.interview.create({
      data: {
        candidateId: candidate.id,
        resumeId: resume.id,
        sector: s.sector,
        roleTitle: s.roleTitle,
        seniority: s.seniority,
        status: "completed",
        completedAt: new Date(),
        plan: JSON.stringify({ questionBudget: 12, targets: [], resumeProbes: [] }),
      },
    });

    await db.assessment.create({
      data: {
        interviewId: interview.id,
        overallScore: s.score,
        recommendation: s.recommendation,
        summary: s.summary,
        competencies: JSON.stringify(s.competencies),
        strengths: JSON.stringify(s.strengths),
        concerns: JSON.stringify(s.concerns),
        integrity: JSON.stringify({
          anomalyScore: 0,
          band: "nothing_notable",
          observations: [],
          counts: {},
          caveat:
            "These are behavioural observations, not proof. Seed data — no real session was monitored.",
        }),
        resumeDeltas: JSON.stringify([]),
      },
    });

    console.log(`  ${s.name} — ${s.score}/100`);
  }

  console.log(`\nDone. ${SEEDS.length} candidates seeded.`);
  console.log('Try the manager search with: "Software engineer who has experience with PyTorch"');
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(() => db.$disconnect());
