/**
 * Demo corpus.
 *
 * These profiles are written directly rather than generated by running real
 * interviews, so `npm run db:seed` works with no API key and costs nothing. The
 * shape matches exactly what the finish route produces, so manager search, the
 * candidate list, and the candidate report render the same way they will with
 * real data.
 *
 * Two things are deliberately *not* hardcoded:
 *   - competency keys are validated against the real criteria files, so a seed
 *     that drifts from the standard fails loudly instead of producing candidates
 *     scored against competencies that no longer exist;
 *   - overall scores are computed by the real scoring function, so the seed
 *     cannot show a number the app's own rule would not produce.
 *
 * Every person here is invented.
 */

import { PrismaClient } from "@prisma/client";
import { embed } from "../src/lib/embeddings";
import { resolveCriteria } from "../src/lib/criteria/load";
import { computeOverall, type ScoredCompetency } from "../src/lib/assess/scoring";

const db = new PrismaClient();

type SeedScore = {
  key: string;
  score: number; // 0-10
  confidence: "low" | "medium" | "high";
  reached?: boolean;
  evidence: string;
  note: string;
};

type Seed = {
  name: string;
  email: string;
  phone: string;
  location: string;
  headline: string;
  roleSlug: string;
  seniority: string;
  years: number;
  recommendation: string;
  summary: string;
  scores: SeedScore[];
  strengths: string[];
  concerns: string[];
  tags: { label: string; kind: string; confidence: number; status: string; evidence: string }[];
};

const SEEDS: Seed[] = [
  {
    name: "Mira Okonkwo",
    email: "mira.okonkwo@example.com",
    phone: "+49 30 5550 1184",
    location: "Berlin",
    headline: "Senior ML engineer, recommendation systems",
    roleSlug: "development",
    seniority: "senior",
    years: 7,
    recommendation: "strong_yes",
    summary:
      "Depth held across three consecutive follow-ups on her own recommender work, including a "
      + "failure she diagnosed herself. Owns mistakes without theatre. Weaker below the model "
      + "layer — the feature store and serving path were vague — which matters if the role owns "
      + "the whole pipeline.",
    scores: [
      { key: "technical_depth", score: 8.9, confidence: "high", evidence: "explained why their two-tower model degraded when the item embedding table was refreshed asynchronously", note: "Depth held up across three consecutive follow-ups." },
      { key: "system_design", score: 7.1, confidence: "medium", evidence: "sketched the candidate-generation and ranking split, but was vague on the feature store", note: "Strong at the model layer, thinner below it." },
      { key: "debugging", score: 8.8, confidence: "high", evidence: "added a shadow ranker to isolate whether the regression was retrieval or ranking", note: "Textbook hypothesis discrimination." },
      { key: "code_quality", score: 7.4, confidence: "medium", evidence: "described dropping test coverage on experiment code deliberately, with a rationale", note: "Has a position and can defend it." },
      { key: "logical_reasoning", score: 8.5, confidence: "high", evidence: "revised her estimate unprompted when told the traffic assumption was 10x off", note: "Updates cleanly on new constraints." },
      { key: "communication", score: 8.0, confidence: "high", evidence: "compressed the whole incident into two sentences when asked", note: "Calibrates depth well." },
      { key: "ownership", score: 8.6, confidence: "high", evidence: "I shipped the async refresh and I did not think about staleness", note: "Owns failure without theatre." },
      { key: "collaboration", score: 7.2, confidence: "medium", evidence: "described losing an architecture argument and implementing the other approach well", note: "Fair to the opposing view." },
    ],
    strengths: [
      "Diagnosed her own production regression and can still explain the discrimination step.",
      "Names the specific decision she got wrong rather than describing it abstractly.",
    ],
    concerns: [
      "Everything below the model layer is thinner than the modelling work itself.",
      "No evidence of owning a service end to end.",
    ],
    tags: [
      { label: "PyTorch", kind: "tool", confidence: 0.92, status: "demonstrated", evidence: "described a custom sampler and why the default one skewed the negatives" },
      { label: "Recommendation systems", kind: "domain", confidence: 0.95, status: "demonstrated", evidence: "two-tower retrieval, candidate generation, ranking split" },
      { label: "Python", kind: "skill", confidence: 0.9, status: "demonstrated", evidence: "" },
      { label: "Embeddings", kind: "skill", confidence: 0.88, status: "demonstrated", evidence: "item embedding staleness diagnosis" },
      { label: "A/B testing", kind: "skill", confidence: 0.76, status: "demonstrated", evidence: "shadow ranker comparison" },
      { label: "Kubernetes", kind: "tool", confidence: 0.3, status: "claimed", evidence: "" },
      { label: "Spark", kind: "tool", confidence: 0.55, status: "claimed", evidence: "" },
      { label: "Feature stores", kind: "domain", confidence: 0.35, status: "claimed", evidence: "" },
    ],
  },
  {
    name: "Daniel Reyes",
    email: "daniel.reyes@example.com",
    phone: "+34 91 555 0472",
    location: "Madrid",
    headline: "Backend engineer, payments and billing",
    roleSlug: "development",
    seniority: "mid",
    years: 4,
    recommendation: "leaning_yes",
    summary:
      "Solid, careful engineer with real production exposure in billing, where correctness "
      + "matters and he clearly knows it. Depth is genuine but narrow — the answers thinned "
      + "noticeably outside his own service. Worth a second conversation on system design.",
    scores: [
      { key: "technical_depth", score: 6.8, confidence: "high", evidence: "explained idempotency keys and why their retry storm double-charged before they existed", note: "Real, but bounded by his own service." },
      { key: "system_design", score: 5.4, confidence: "medium", evidence: "reached for a queue without saying what it bought him", note: "Names patterns faster than constraints." },
      { key: "debugging", score: 7.6, confidence: "high", evidence: "traced a reconciliation mismatch to a timezone boundary in a nightly job", note: "Methodical, verified the fix." },
      { key: "code_quality", score: 7.2, confidence: "medium", evidence: "described a refactor he argued against and why he was wrong", note: "" },
      { key: "logical_reasoning", score: 6.4, confidence: "medium", evidence: "restated the question once before advancing on it", note: "" },
      { key: "communication", score: 7.0, confidence: "high", evidence: "", note: "Clear, if slightly over-detailed." },
      { key: "ownership", score: 7.4, confidence: "high", evidence: "I approved that migration and I did not check the backfill", note: "" },
      { key: "collaboration", score: 6.6, confidence: "low", evidence: "", note: "Barely tested — one brief example." },
    ],
    strengths: [
      "Understands why correctness discipline exists in billing rather than following it by rote.",
      "Owns a migration mistake with specifics.",
    ],
    concerns: [
      "Design answers reach for named patterns before constraints.",
      "Experience is narrow to one service; breadth untested.",
    ],
    tags: [
      { label: "Go", kind: "tool", confidence: 0.82, status: "demonstrated", evidence: "" },
      { label: "PostgreSQL", kind: "tool", confidence: 0.85, status: "demonstrated", evidence: "reconciliation query walkthrough" },
      { label: "Payments", kind: "domain", confidence: 0.88, status: "demonstrated", evidence: "idempotency and retry storms" },
      { label: "Idempotency", kind: "skill", confidence: 0.9, status: "demonstrated", evidence: "double-charge incident" },
      { label: "Kafka", kind: "tool", confidence: 0.4, status: "claimed", evidence: "" },
      { label: "Distributed systems", kind: "domain", confidence: 0.45, status: "claimed", evidence: "" },
      { label: "Docker", kind: "tool", confidence: 0.7, status: "demonstrated", evidence: "" },
    ],
  },
  {
    name: "Hana Sato",
    email: "hana.sato@example.com",
    phone: "+81 3 5550 2288",
    location: "Tokyo",
    headline: "ML researcher turned applied engineer, computer vision",
    roleSlug: "development",
    seniority: "senior",
    years: 8,
    recommendation: "yes",
    summary:
      "Exceptional depth in vision models and training dynamics, with a research background that "
      + "shows in how carefully she qualifies claims. Production and reliability concerns are "
      + "noticeably less developed than her modelling work, and she says so herself.",
    scores: [
      { key: "technical_depth", score: 9.2, confidence: "high", evidence: "explained why their augmentation pipeline broke batch-norm statistics at small batch sizes", note: "Very deep, holds across follow-ups." },
      { key: "system_design", score: 5.5, confidence: "medium", evidence: "vague on inference serving and latency budgets", note: "Research-shaped, not production-shaped." },
      { key: "debugging", score: 8.4, confidence: "high", evidence: "bisected a training divergence to a specific mixed-precision overflow", note: "" },
      { key: "code_quality", score: 6.0, confidence: "medium", evidence: "acknowledged research code that nobody could rerun", note: "Honest about it." },
      { key: "logical_reasoning", score: 8.6, confidence: "high", evidence: "qualified a claim unprompted when the evaluation set was questioned", note: "" },
      { key: "communication", score: 7.4, confidence: "high", evidence: "defined the jargon that mattered and skipped the jargon that did not", note: "" },
      { key: "ownership", score: 7.2, confidence: "medium", evidence: "", note: "" },
      { key: "collaboration", score: 7.0, confidence: "medium", evidence: "", note: "" },
    ],
    strengths: [
      "Training-dynamics knowledge that survived three levels of follow-up.",
      "Qualifies claims carefully and volunteers the limits of her own evaluations.",
    ],
    concerns: [
      "Production serving, latency, and reliability are underdeveloped relative to modelling.",
      "Research-code habits would need adjusting for a production team.",
    ],
    tags: [
      { label: "PyTorch", kind: "tool", confidence: 0.96, status: "demonstrated", evidence: "batch-norm statistics under small-batch augmentation" },
      { label: "Computer vision", kind: "domain", confidence: 0.94, status: "demonstrated", evidence: "" },
      { label: "CUDA", kind: "tool", confidence: 0.7, status: "demonstrated", evidence: "mixed-precision overflow diagnosis" },
      { label: "Distributed training", kind: "skill", confidence: 0.8, status: "demonstrated", evidence: "" },
      { label: "Python", kind: "skill", confidence: 0.92, status: "demonstrated", evidence: "" },
      { label: "ONNX", kind: "tool", confidence: 0.4, status: "claimed", evidence: "" },
      { label: "Model evaluation", kind: "skill", confidence: 0.85, status: "demonstrated", evidence: "" },
      { label: "Transformers", kind: "skill", confidence: 0.82, status: "demonstrated", evidence: "" },
    ],
  },
  {
    name: "Adaeze Balogun",
    email: "adaeze.balogun@example.com",
    phone: "+44 20 7555 0913",
    location: "London",
    headline: "Curriculum lead, professional technical education",
    roleSlug: "education-planning",
    seniority: "lead",
    years: 11,
    recommendation: "strong_yes",
    summary:
      "Has rebuilt a course after watching it fail and can describe exactly which sequencing "
      + "assumption was wrong. Assessment design is the standout: she writes tasks that can "
      + "actually fail a learner and treats that as the point. Stakeholder answers were strong "
      + "but drawn from a narrow set of institutions.",
    scores: [
      { key: "curriculum_design", score: 9.0, confidence: "high", evidence: "we had them writing queries before they understood what a join was, and the dropout was all in week three", note: "Reordered a live course on evidence." },
      { key: "learner_evidence", score: 8.4, confidence: "high", evidence: "the satisfaction scores were the highest we ever got on the cohort that learned the least", note: "Knows liking is not learning." },
      { key: "assessment_design", score: 8.8, confidence: "high", evidence: "described rewriting an exam where every learner passed and explaining why that was a failure", note: "Rare clarity on discrimination." },
      { key: "stakeholder_translation", score: 7.6, confidence: "medium", evidence: "pushed back on an executive request to shorten the practical module and lost", note: "Handled the loss well." },
      { key: "logical_reasoning", score: 7.8, confidence: "medium", evidence: "", note: "" },
      { key: "communication", score: 8.8, confidence: "high", evidence: "structured every answer before diving in", note: "" },
      { key: "ownership", score: 8.5, confidence: "high", evidence: "I designed that sequence and I did not test the prerequisite assumption", note: "" },
      { key: "collaboration", score: 8.2, confidence: "high", evidence: "stated the engineering lead's objection fairly before disagreeing with it", note: "" },
    ],
    strengths: [
      "Redesigned a live course from dropout evidence and can name the assumption that was wrong.",
      "Treats an exam everyone passes as a defect, and can explain why.",
      "Represents positions she lost fairly.",
    ],
    concerns: [
      "All experience is in one institutional context; portability untested.",
      "Less evidence of working with subject experts who resist being structured.",
    ],
    tags: [
      { label: "Curriculum design", kind: "skill", confidence: 0.94, status: "demonstrated", evidence: "prerequisite resequencing" },
      { label: "Assessment design", kind: "skill", confidence: 0.92, status: "demonstrated", evidence: "rewrote a non-discriminating exam" },
      { label: "Learning analytics", kind: "skill", confidence: 0.8, status: "demonstrated", evidence: "week-three dropout analysis" },
      { label: "Technical education", kind: "domain", confidence: 0.9, status: "demonstrated", evidence: "" },
      { label: "Instructional design", kind: "skill", confidence: 0.85, status: "demonstrated", evidence: "" },
      { label: "LMS platforms", kind: "tool", confidence: 0.5, status: "claimed", evidence: "" },
      { label: "Stakeholder management", kind: "soft", confidence: 0.72, status: "demonstrated", evidence: "" },
    ],
  },
  {
    name: "Tomás Ferreira",
    email: "tomas.ferreira@example.com",
    phone: "+351 21 555 0330",
    location: "Lisbon",
    headline: "Programme designer, developer education",
    roleSlug: "education-planning",
    seniority: "mid",
    years: 5,
    recommendation: "leaning_yes",
    summary:
      "Good instincts about where learners get stuck and a genuine example of cutting content he "
      + "had championed. Evidence discipline is the weak spot — described completion rates rising "
      + "without a baseline and did not engage when the confound was raised. Worth a second "
      + "conversation focused on how he would measure a change.",
    scores: [
      { key: "curriculum_design", score: 7.0, confidence: "high", evidence: "cut a module he had written because learners kept skipping it to reach the project", note: "Willing to cut his own work." },
      { key: "learner_evidence", score: 4.2, confidence: "high", evidence: "completion went up 20% after we shipped it, with nothing to compare against", note: "Attributes causally without a design." },
      { key: "assessment_design", score: 5.6, confidence: "medium", evidence: "described a project rubric but not what it would fail", note: "Assessment as feedback, not measurement." },
      { key: "stakeholder_translation", score: 6.8, confidence: "medium", evidence: "extracted a working outline from an engineer who talked in war stories", note: "" },
      { key: "logical_reasoning", score: 5.5, confidence: "medium", evidence: "did not notice the confound when it was raised", note: "" },
      { key: "communication", score: 7.2, confidence: "high", evidence: "", note: "" },
      { key: "ownership", score: 6.8, confidence: "medium", evidence: "", note: "" },
      { key: "collaboration", score: 6.5, confidence: "low", reached: false, evidence: "", note: "The interview did not reach this competency." },
    ],
    strengths: [
      "Cut a module he had personally written, on evidence that learners routed around it.",
      "Can pull structure out of a subject expert who thinks in anecdotes.",
    ],
    concerns: [
      "Treats a metric moving as proof the change caused it; no baseline or comparison discipline.",
      "Did not engage when the confound was pointed out.",
    ],
    tags: [
      { label: "Developer education", kind: "domain", confidence: 0.8, status: "demonstrated", evidence: "" },
      { label: "Curriculum design", kind: "skill", confidence: 0.72, status: "demonstrated", evidence: "module cut on routing evidence" },
      { label: "Learner research", kind: "skill", confidence: 0.65, status: "demonstrated", evidence: "" },
      { label: "Learning analytics", kind: "skill", confidence: 0.2, status: "contradicted", evidence: "no baseline in the example given" },
      { label: "Technical writing", kind: "skill", confidence: 0.75, status: "demonstrated", evidence: "" },
      { label: "Workshop facilitation", kind: "soft", confidence: 0.45, status: "claimed", evidence: "" },
    ],
  },
  {
    name: "Sofia Lindqvist",
    email: "sofia.lindqvist@example.com",
    phone: "+46 8 555 0167",
    location: "Stockholm",
    headline: "Enterprise account executive, compliance software",
    roleSlug: "b2b-sales",
    seniority: "senior",
    years: 9,
    recommendation: "yes",
    summary:
      "Knows her own numbers to a level most candidates cannot fake, and volunteered a forecast "
      + "she got badly wrong before being asked. Qualifies out honestly. Communication is dense "
      + "and assumes the listener's context, which would need work for a role that presents to "
      + "committees.",
    scores: [
      { key: "discovery", score: 8.6, confidence: "high", evidence: "the stated requirement was SSO and the actual problem was an audit finding they had 60 days to close", note: "Consistently reaches the real driver." },
      { key: "pipeline_rigour", score: 9.0, confidence: "high", evidence: "quoted a 22% stage-three conversion and explained why it dropped after they changed qualification", note: "Numbers survived every follow-up." },
      { key: "objection_handling", score: 7.4, confidence: "medium", evidence: "described learning the price objection was really a procurement timing problem", note: "" },
      { key: "commercial_judgement", score: 8.2, confidence: "high", evidence: "held price on a deal she then lost, and still thinks it was right", note: "Thinks past the quarter." },
      { key: "logical_reasoning", score: 7.8, confidence: "medium", evidence: "identified that her own conclusion did not follow when the renewal horizon changed", note: "" },
      { key: "communication", score: 5.8, confidence: "high", evidence: "three requests for a plainer restatement before it landed", note: "Dense; assumes the listener's context." },
      { key: "ownership", score: 8.0, confidence: "high", evidence: "I forecast that deal at 90% in the board pack and it never closed", note: "" },
      { key: "collaboration", score: 7.4, confidence: "medium", evidence: "described a disagreement with solutions engineering fairly", note: "" },
    ],
    strengths: [
      "Reports her own numbers accurately under repeated follow-up.",
      "Volunteers a forecast she got wrong, with what she changed afterwards.",
      "Held a price and can defend the decision despite losing the deal.",
    ],
    concerns: [
      "Explanations are dense; a committee-facing role would need coaching.",
      "All experience is in one product category.",
    ],
    tags: [
      { label: "Enterprise sales", kind: "domain", confidence: 0.94, status: "demonstrated", evidence: "" },
      { label: "MEDDIC", kind: "skill", confidence: 0.7, status: "demonstrated", evidence: "qualification change and its conversion effect" },
      { label: "Compliance software", kind: "domain", confidence: 0.88, status: "demonstrated", evidence: "" },
      { label: "Forecasting", kind: "skill", confidence: 0.9, status: "demonstrated", evidence: "stage-three conversion walkthrough" },
      { label: "Salesforce", kind: "tool", confidence: 0.75, status: "demonstrated", evidence: "" },
      { label: "Procurement navigation", kind: "skill", confidence: 0.8, status: "demonstrated", evidence: "" },
      { label: "Channel partnerships", kind: "domain", confidence: 0.35, status: "claimed", evidence: "" },
    ],
  },
];

const SEED_INTEGRITY = JSON.stringify({
  anomalyScore: 0,
  band: "nothing_notable",
  observations: [],
  counts: {},
  caveat:
    "These are behavioural observations, not proof. Seed data — no real session was monitored.",
});

async function main() {
  console.log("Seeding demo candidates…");

  // Load every criteria file the seed references. This also creates the
  // CriteriaSet rows, so a fresh database has the standard in it before any
  // candidate is attached to one.
  const slugs = [...new Set(SEEDS.map((s) => s.roleSlug))];
  const criteriaBySlug = new Map(
    await Promise.all(
      slugs.map(async (slug) => [slug, await resolveCriteria(slug)] as const),
    ),
  );

  for (const s of SEEDS) {
    const criteria = criteriaBySlug.get(s.roleSlug);
    if (!criteria) throw new Error(`No criteria for ${s.roleSlug}`);

    // Seed scores are matched against the real criteria file rather than trusted.
    // If someone edits a criteria file and forgets the seed, this is where they
    // find out — rather than in a candidate report with blank axes.
    const byKey = new Map(s.scores.map((x) => [x.key, x]));
    const unknown = s.scores.filter((x) => !criteria.competencies.some((c) => c.key === x.key));
    if (unknown.length) {
      throw new Error(
        `${s.name}: scores reference competencies that criteria/${s.roleSlug}.md does not define: `
        + `${unknown.map((u) => u.key).join(", ")}`,
      );
    }

    const scored: ScoredCompetency[] = criteria.competencies.map((c) => {
      const x = byKey.get(c.key);
      return {
        competencyKey: c.key,
        label: c.label,
        score: x?.score ?? 0,
        priority: c.priority,
        confidence: x?.confidence ?? "low",
        evidenceQuote: x?.evidence ?? "",
        note: x?.note ?? "This competency was not covered by the interview.",
        source: "interview" as const,
        reached: x ? x.reached !== false : false,
      };
    });

    // The same function the app uses, so the seed cannot display a number the
    // real scoring rule would not produce.
    const overall = computeOverall(scored);

    const competenciesJson = JSON.stringify(
      scored.map((x) => ({
        competencyId: x.competencyKey,
        label: x.label,
        score: x.score,
        priority: x.priority,
        confidence: x.confidence,
        reached: x.reached,
        evidence: x.evidenceQuote,
        note: x.note,
        source: x.source,
      })),
    );

    const candidate = await db.candidate.upsert({
      where: { email: s.email },
      create: {
        email: s.email,
        name: s.name,
        phone: s.phone,
        location: s.location,
        consentInterview: true,
        consentRecording: true,
        consentLinkCheck: false,
        // So the cross-role compare control is exercisable straight after a seed.
        consentCrossRole: true,
        consentedAt: new Date(),
        consentPolicyVer: "2026-08-23",
      },
      update: {
        name: s.name, phone: s.phone, location: s.location, consentCrossRole: true,
      },
    });

    const searchText = [
      s.headline,
      `${s.seniority} ${criteria.roleTitle}`,
      criteria.sector,
      s.summary,
      s.tags
        .flatMap((t) =>
          Array.from(
            { length: t.status === "demonstrated" ? Math.max(1, Math.ceil(t.confidence * 3)) : 1 },
            () => t.label,
          ),
        )
        .join(" "),
      scored.filter((x) => x.reached).map((x) => `${x.label} ${x.note}`).join(" "),
    ].join("\n");

    const embedding = await embed(searchText);

    const profileFields = {
      headline: s.headline,
      sector: criteria.sector,
      roleSlug: criteria.roleSlug,
      roleTitle: criteria.roleTitle,
      seniority: s.seniority,
      yearsExperience: s.years,
      overallScore: overall.overall,
      recommendation: s.recommendation,
      summary: s.summary,
      searchText,
      embedding: JSON.stringify(embedding),
      competencies: competenciesJson,
    };

    await db.candidateProfile.upsert({
      where: { candidateId: candidate.id },
      create: { candidateId: candidate.id, ...profileFields },
      update: profileFields,
    });

    for (const t of s.tags) {
      const tag = await db.tag.upsert({
        where: { label: t.label },
        create: { label: t.label, kind: t.kind },
        update: {},
      });
      await db.candidateTag.upsert({
        where: { candidateId_tagId: { candidateId: candidate.id, tagId: tag.id } },
        create: {
          candidateId: candidate.id,
          tagId: tag.id,
          confidence: t.confidence,
          status: t.status,
          evidence: t.evidence || null,
        },
        update: { confidence: t.confidence, status: t.status },
      });
    }

    // Re-running the seed must not stack up duplicate interviews for the same
    // invented person.
    await db.interview.deleteMany({ where: { candidateId: candidate.id } });
    await db.resume.deleteMany({ where: { candidateId: candidate.id } });

    const resume = await db.resume.create({
      data: {
        candidateId: candidate.id,
        filename: "seed.txt",
        mimeType: "text/plain",
        rawText: `${s.name}\n${s.headline}\n(seed data)`,
        extracted: JSON.stringify({
          name: s.name, headline: s.headline, totalYearsExperience: s.years,
          employment: [], education: [], skills: [], notableClaims: [], links: [],
          email: s.email, phone: s.phone, location: s.location, summary: s.summary,
          sector: criteria.sector, seniority: s.seniority, gapsOrOddities: [],
        }),
      },
    });

    // Backdated, and deliberately so. startedAt defaults to now(), and the daily
    // spend cap in src/lib/gate.ts counts interviews started since midnight UTC
    // — so demo rows created at deploy time would eat a real candidate's slot,
    // and every redeploy would eat six more. Dated a week back, they never
    // collide with a live cap.
    const seededAt = new Date(Date.now() - 7 * 24 * 3600 * 1000);

    const interview = await db.interview.create({
      data: {
        candidateId: candidate.id,
        resumeId: resume.id,
        criteriaSetId: criteria.criteriaSetId,
        roleSlug: criteria.roleSlug,
        sector: criteria.sector,
        roleTitle: criteria.roleTitle,
        seniority: s.seniority,
        status: "completed",
        startedAt: seededAt,
        completedAt: seededAt,
        plan: JSON.stringify({
          criteria: {
            criteriaSetId: criteria.criteriaSetId,
            roleSlug: criteria.roleSlug,
            roleTitle: criteria.roleTitle,
            sector: criteria.sector,
            version: criteria.version,
            sourcePath: criteria.sourcePath,
            sourceHash: criteria.sourceHash,
            competencies: criteria.competencies.map((c) => ({
              id: c.key,
              label: c.label,
              description: c.description,
              probes: c.strongAnswer,
              weakSignals: c.weakAnswer,
              priority: c.priority,
            })),
          },
          sector: criteria.sector,
          roleTitle: criteria.roleTitle,
          seniority: s.seniority,
          questionBudget: 12,
          targets: criteria.competencies.map((c) => ({
            competencyId: c.key,
            label: c.label,
            targetQuestions: c.priority === "high" ? 2 : 1,
          })),
          resumeProbes: [],
          openingQuestion: "(seed data — no interview was conducted)",
          focusRationale: "Seed data.",
          createdAt: new Date().toISOString(),
        }),
      },
    });

    await db.assessment.create({
      data: {
        interviewId: interview.id,
        criteriaSetId: criteria.criteriaSetId,
        overallScore: overall.overall,
        recommendation: s.recommendation,
        summary: s.summary,
        competenciesCounted: overall.counted,
        competenciesTotal: overall.total,
        competencies: competenciesJson,
        strengths: JSON.stringify(s.strengths),
        concerns: JSON.stringify(s.concerns),
        integrity: SEED_INTEGRITY,
        resumeDeltas: JSON.stringify([]),
        scores: {
          create: scored.map((x) => ({
            competencyKey: x.competencyKey,
            label: x.label,
            score: x.score,
            confidence: x.confidence,
            evidenceQuote: x.evidenceQuote,
            note: x.note,
            source: x.source,
            reached: x.reached,
          })),
        },
      },
    });

    console.log(
      `  ${s.name.padEnd(18)} ${criteria.roleTitle.padEnd(28)} `
      + `${String(overall.overall).padStart(3)}/100  (${overall.counted}/${overall.total} competencies)`,
    );
  }

  console.log(`\nDone. ${SEEDS.length} candidates across ${slugs.length} roles.`);
  console.log('Try the manager search with: "Software engineer who has experience with PyTorch"');
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(() => db.$disconnect());
